name:                DiffPrivacyInferenceHs
version:             0.1.0.0
github:              "githubuser/DiffPrivacyInferenceHs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DiffPrivacyInferenceHs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - text
    - mtl
    - lens
    - bifunctors
    - data-default
    - hashable
    - unordered-containers
    - singletons
    - newtype
    - constraints
    # - computational-algebra
    # - type-natural
    # - algebra
    # - algebraic-prelude
    # - halg-core
    # - halg-core-test
    # - halg-polyn-parser
    # - halg-polynomials
    # - halg-galois-fields
    # - halg-matrices
    # - halg-algorithms
    # - halg-factor
    # - halg-algebraic
  default-extensions:
    - QuasiQuotes
    - ConstraintKinds
    - DataKinds
    - GADTs
    - KindSignatures
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - NoMonomorphismRestriction
    - TypeOperators
    - UnicodeSyntax
    - ExistentialQuantification
    - ScopedTypeVariables
    - QuantifiedConstraints
    - KindSignatures
    - PolyKinds
    - GeneralizedNewtypeDeriving
    - DeriveGeneric
    - StandaloneDeriving 
    - DerivingVia
    - FlexibleInstances
    - FlexibleContexts
    - FunctionalDependencies
    - OverloadedStrings
    - TypeApplications
    - TypeFamilies
    - RankNTypes
    - OverloadedStrings
    - StandaloneKindSignatures
    - LambdaCase
    - DisambiguateRecordFields
    - DuplicateRecordFields



executables:
  diffmu:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DiffPrivacyInferenceHs
    default-extensions:
    - OverloadedStrings
    - TypeApplications
    - DataKinds

tests:
  DiffPrivacyInferenceHs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DiffPrivacyInferenceHs
